version: '3.5'
services:
  tor-server:
    build: 
      context: ./tor-server
    image: darkgate/tor-server:2019.10.26
    networks:
      dark-net:
        aliases:
          - dark
  i2p-server:
    build:
      context: ./i2p-server
    image: darkgate/i2p-server:2019.10.26
    ports:
      - 2827:2827 # BOB port
      - 4444:4444 # HTTP proxy
      - 6668:6668 # Proxy to Irc2P
      - 7656:7656 # SAM port
      - 7657:7657 # router console
      - 7658:7658 # self-hosted eepsite
      - 7659:7659 # SMTP proxy to smtp.postman.i2p
      - 7660:7660 # POP3 proxy to pop.postman.i2p
      - 8998:8998 # Proxy to mtn.i2p-projekt.i2p
    networks:
      - dark-net

  privoxy-server:
    build: 
      context: ./privoxy-server
    image: darkgate/privoxy-server:2019.10.26
    volumes:
      - type: bind
        source: ./privoxy-server/config
        target: /etc/privoxy/config
        volume:
          nocopy: true
    ports:
      - 8118:8118
    networks:
      - dark-net
    depends_on:
      - tor-server

networks:
  dark-net:
    driver: bridge
